### ISSUE TITLE
Newest version of xlrd doesn't support .xlsx files

### ISSUE THREAD

**Issue by oobayly** [selinabayly/UCDPA_Bayly_Selina#1]
The newest version (2.0.1) of xlrd no longer supports .xlsx files - see [[Solved] xlrd.biffh.XLRDError: Excel xlsx file; not supported in python](https://exerror.com/xlrd-biffh-xlrderror-excel-xlsx-file-not-supported/).

Excluding using an outdated version of xlrd, two solutions are provided:
1. Use a plaintext CSV file and use the `panda.read_csv` method.
2. Explicitly using the `openpyxl` engine.

**Comment by selinabayly** [comment]
Thanks John.  Have changed to CSV now.
